<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TrollIt.Domain\TrollIt.Domain.csproj" />
    <ProjectReference Include="..\TrollIt.Application\TrollIt.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.DependencyInjection" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
    <InternalsVisibleTo Include="TrollIt.Application.Tests" />
    <InternalsVisibleTo Include="TrollIt.Api.Tests" />
  </ItemGroup>

</Project>
