name: TrollIt CI
on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  build:
    name: Build and analyze
    uses: ./.github/workflows/dotnet.yml
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      sonar: ${{ github.event_name == 'pull_request' || startsWith(github.ref, 'refs/tags/') || github.ref_name == 'main' || github.ref_name == 'develop' }}
      publish: ${{ github.event_name != 'pull_request' }}
  package:
    name: Build image and push to registry
    uses: ./.github/workflows/deploy.yml
    if: success() && github.event_name != 'pull_request'
    needs: build
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      registry: ghcr.io/geoff32
      image-name: trollit/api
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write